In [43]:
import numpy as np

In [44]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [45]:
price_list2 = [43, 41, 42.9,44.2]
price_array2 = np.array(price_list2)
print(price_array2, type(price_array2))

[43.  41.  42.9 44.2] <class 'numpy.ndarray'>


In [46]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [47]:
Ar2 = np.array([[0,2],[1,3]])
print(Ar2, type(Ar2))

[[0 2]
 [1 3]] <class 'numpy.ndarray'>


In [48]:
print(Ar.shape)

(2, 2)


In [49]:
print(Ar2.shape)

(2, 2)


In [50]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [51]:
print(Ar2[1])
print(Ar2[0])

[1 3]
[0 2]


In [52]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


In [53]:
print('Primera columna: ', Ar2[:,0])
print('Segunda columna: ', Ar2[:,1])

Primera columna:  [0 1]
Segunda columna:  [2 3]


In [54]:
print(np.log(price_array))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]


In [55]:
print(np.log(price_array2))

[3.76120012 3.71357207 3.75887183 3.78872479]


In [56]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [57]:
print(np.mean(price_array2))
print(np.std(price_array2))
print(np.sum(price_array2))
print(np.max(price_array2))

42.775000000000006
1.1453711188955316
171.10000000000002
44.2


In [58]:
import pandas as pd

In [59]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

In [60]:
price2 = [43, 41, 42.9,44.2]
s2 = pd.Series(price2)
s2

0    43.0
1    41.0
2    42.9
3    44.2
dtype: float64

In [61]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

In [62]:
s2 = pd.Series(price2,index = ['A','B','C','D'])
s2

A    43.0
B    41.0
C    42.9
D    44.2
dtype: float64

In [63]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

In [64]:
s2.index = [4,3,2,1]
s2

4    43.0
3    41.0
2    42.9
1    44.2
dtype: float64

In [65]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [66]:
print(s2[1:])
print(s2[:-2])

3    41.0
2    42.9
1    44.2
dtype: float64
4    43.0
3    41.0
dtype: float64


In [67]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [68]:
print(s2[3])
s2[4] = 0.1
print(s2)

41.0
4     0.1
3    41.0
2    42.9
1    44.2
dtype: float64


In [69]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


In [70]:
s2 = pd.Series(price2, name = 'Precios de algo')
print(s2)
print(s2.name)

0    43.0
1    41.0
2    42.9
3    44.2
Name: Precios de algo, dtype: float64
Precios de algo


In [71]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


In [72]:
time_index2 = pd.date_range('2018-01-01',periods = len(s2),freq = 'D')
print(time_index2)
s2.index = time_index2
print(s2)

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04'], dtype='datetime64[ns]', freq='D')
2018-01-01    43.0
2018-01-02    41.0
2018-01-03    42.9
2018-01-04    44.2
Freq: D, Name: Precios de algo, dtype: float64


In [73]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


In [74]:
s2.index = [4,3,2,1]
print(s2)
print(s2[2])

4    43.0
3    41.0
2    42.9
1    44.2
Name: Precios de algo, dtype: float64
42.9


In [75]:
print(s.iloc[1])

145.83


In [76]:
print(s2.iloc[3])

44.2


In [77]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [78]:
s2.index = time_index2
print(s2['2018-01-04'])

44.2


In [79]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Price List, dtype: float64


In [80]:
print(s2['2018-01-02':'2018-01-4'])

2018-01-02    41.0
2018-01-03    42.9
2018-01-04    44.2
Freq: D, Name: Precios de algo, dtype: float64


In [81]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Price List, dtype: float64
[2017-01-01    False
2017-01-02    False
2017-01-03    False
2017-01-04     True
2017-01-05    False
2017-01-06    False
Freq: D, Name: Apple Price List, dtype: bool]


In [82]:
print(s2[s2 < np.mean(s2)] )
print([(s2 > np.mean(s2)) & (s2 < np.mean(s2) + 1.64*np.std(s2))])

2018-01-02    41.0
Freq: D, Name: Precios de algo, dtype: float64
[2018-01-01     True
2018-01-02    False
2018-01-03     True
2018-01-04     True
Freq: D, Name: Precios de algo, dtype: bool]
